title: Paweł Izdebski
name: Paweł Izdebski Official
baseurl: "" # production
# baseurl: "" #development
# url: "http://localhost:4000" # development
url: "https://pawelizdebski.pl" # production domain
copyright: 2018 © <a href="https://pawelizdebski.pl" class="site-link">Paweł Izdebski</a>. Wszelkie prawa zastrzeżone.
copyright_short: 2018 © <a href="https://pawelizdebski.pl" class="site-link">Paweł Izdebski</a>.
made_by: 'Made with ❤ by DW'
# Build settings
markdown: kramdown
incremental: true
spotify_url: 'https://open.spotify.com/album/2DM2GLKv3N1FObQGcH2Gj9'
youtube_url: 'https://www.youtube.com/c/PawelIzdebski/'
instagram_url: 'https://www.instagram.com/nieokiemznany/'
twitter_url: 'https://twitter.com/IzdebskiGra'
facebook_url: 'https://www.facebook.com/pawelizdebskipl'
permalink: /blog/:title/
news_path: '/news'
news_page_layout: 'report'
gems:
  - jekyll-watch
  - jekyll-paginate-v2
  - jekyll-assets
  - jekyll-redirect-from
exclude:
- CNAME
- .gitignore
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor
- .ruby-version
- Guardfile
- .jekyll-assets-cache
- .sass-cache
- .editorconfig
- .idea
- .ruby-version
- .asset-cache
- _docs

#
# Plugin: jekyll-assets
#
assets:
  cache: false
  features:
    automatic_img_size: false
    automatic_img_alt: false

pagination:
  enabled: true
  collection: posts
  per_page: 4
  permalink: '/page:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
